.\" Manpage for napi-bash.conf.
.TH NAPI-BASH 3 "2014-06-11" "0.50" "Programowanie napi-bash"
.SH NAZWA
Przeprogramowywanie napi-bash lub używanie jako biblioteki dla zewnętrznego programu.
.br
.B UWAGA:
To dopiero wczesna wersja przed-rozwojowa, w każdej chwili mogą nastąpić zmiany...
.SH SKŁADNIA
.SS Bash (bezpośrednio)
.nf
source /usr/bin/napi-bash

moja_funkcja() {
  usage
}

moja_funkcja
.fi
.SS Perl
.nf
use IPC::Open3;

my $cmd = <<EOF
source /usr/bin/napi-bash

moja_funkcja() {
  usage
}

moja_funkcja
EOF

my $pid = open3(
    \\*IN, \\*OUT, \\*ERR,
    'bash <<< "' . $cmd . '"'
);

print while (<OUT>)
.fi
.SS Python
TODO
.SS C
TODO
.SH FUNKCJE
.SH ZMIENNE
.SH ZOBACZ TEŻ
.BR napi-bash (1)
.BR napi-bash (5)
