.\" Manpage for napi-bash.conf.
.TH NAPI-BASH 5 "2014-05-15" "0.41" "Konfiguracja napi-bash"
.SH NAZWA
Konfiguracja programu napi-bash..
.SH LOKALIZACJA
${XDG_CONFIG_HOME}/napi-bash/config
.br
~/.config/napi-bash/config
.SH OPIS
Program załaduje ten plik jako część swojego kodu, nadpisując zdefiniowanymi w nim domyślne opcje i niektóre funkcje..
.SH OPCJE KONFIGURACYJNE
.SS
.nf
suboverwrite, skipifexist, colors, subext, subext_autodetect, subext-prefix, subfmt_conv, subcp_conv, subeol_conv
.fi
.TS
tab(#);
|l|l|.
_
Opcja konfiguracji#Argument polecenia
_
suboverwrite=*#-o=xyz, --suboverwrite=*
_
skipifexist=*#-s=*, --skipifexist=*
_
colors=*#-c=*|--colors=*
_
subext=*#-x=*, --subext=*
_
subext_autodetect=*#-X=*, --subext-autodetect=*
_
subext-prefix=*#-P=*, --subext-prefix=*
_
subfmt_conv=*#-F=*, --subfmt-conv=*
_
subcp_conv=*#-C=*, --subcp-conv=*
_
subeol_conv=*#-E=*, --subeol-conv=*
_
.TE
Patrz:
.BR napi-bash (1)
.SS auth_nick=login
Twój login do napiprojektu. Domyślnie puste czyli jako anonim.
.br
.B Uwaga:
transmisja czystym tekstem bez zapamiętywania sesji...
.SS auth_pass=haslo
Twoje hasło do napiprojektu. Patrz:
.B auth_nick
.SS subfmt_ext[Format]="Rozszerzenie"
Opcja umożliwia zmianę domyślnego rozszerzenia formatu. Obsługiwanie formaty i ich rozszerzenia:
.TS
tab(#);
|l|l|.
_
Format:#Rozszerzenie:
_
fab#txt
_
microdvd#sub
_
mpl2#txt
_
subviewer#sub
_
subrip#srt
_
tmplayer#txt
_
.TE
.SS
.nf
videoext=(.3gp .avi .asf .divx .m4v .mkv .mov .mp4 .mpe .mpeg .mpg .ogg .ogv .rmvb .wmv .qt)
.fi
Rozszerzenia jakie mogą mieć pliki filmowe.. Używaj tylko małych liter. Można stosować „Brace expansion”, np:
.nf
videoext=(.{3gp,avi,asf,divx,m{4,k,o}v,mp{4,e,eg,g},ogg,ogv,rmvb,wmv,qt})
.fi
.SS DLAGENT="curl -fLsS --retry 3 --retry-delay 3 -o %o %u"
Agent pobierania plików (%o wyjściowy; %u adres url)
.SS msg_status[ID]="Treść"
Format wyjścia dla notyfikacji "Status". Notyfikacja pojawia się za każdym razem gdy program zakończył operacje dla pojedyńczego pliku, chyba że wyłączono w `msg_{cli,gui}_disabled_array'. Zobacz też sekcje
.B TAGI.
Domyślne ustawienia:
.TS
tab(#);
|l|l|.
_
ID:#Treść:
_
0#%2%bPobrano%R dla %i%f
_
1#%1%bBrak napisów%R dla %i%f
_
2#%1Brak uprawnień do zapisu w folderze z plikiem: %f
_
3#%1Niewystarczająca ilość wolnego miejsca na urządzeniu z plikiem: %f
_
100#%1Niepowiodła sie detekcja formatu napisów dla: %f
_
101#%1Niepowiodło się konwertowanie formatu napisów dla: %f
_
254#%1DLAGENT nie zawiera tagu %o dla pliku wyjściowego..
_
255#%1Pobieranie pliku z napisami nie powiodło się, problemy z połączeniem?
_
.TE
.SS msg_cli_disabled_array=()
.SS msg_gui_disabled_array=(0 1)
Wyłącz info dla następujących treści (patrz na msg_status) #tablica id
.br
Uwaga: 0 i 1 mogą być męczące w Gnome3 (domyślnie wyłączone)
.SS msg_raport=""
Format wyjścia dla notyfikacji "Raport". Notyfikacja pojawia się tylko raz tuż po wykonaniu wszystkich zadań podsumowując je, chyba że wyłączono w `raport_{cli,gui}_enabled'. Zobacz też sekcje
.B TAGI.
.SS raport_cli_enabled=1
.SS raport_gui_enabled=1
Wyświetlaj raport końcowy (fałsz/prawda) #0/1
.SS gui_int_warn=1
Wyświetlaj notyfikacje dla uwag nie odnoszących się bezpośrednio do pobieranych napisów. Np: informacje o brakujących programach pomocniczych... (fałsz/prawda) #0/1
.SH ZAAWANSOWANE OPCJE KONFIGURACYJNE
.B Modyfikujesz na własną odpowiedzialność!
.SS subfmt_lasting_time="3000"
Minimalny czas wyświetlania linijki w ms dla napisów konwertowanych z formatu w którym nie ma określonego czasu wygasania.
.SS gui_msg_fmt="gui_xml"
.SS cli_msg_fmt="cli_esc"
.SS gui_raport_fmt="gui_xml"
.SS cli_raport_fmt="cli_esc"
Domyślne moduły parsowania tagów formatowania tekstu. użytkownik może stworzyć własne. Należy pamiętać że aby nie tworzyć konfliktów z modułami parsowania tagów informacji, powinno się używać tylko następujących tagów: %b, %i, %u, %B, %I, %U, %R, %[0-9]. Aby napisać inny format, stwórz funkcję _fmt_fields_nowy_format i nadpisz zmienną, np: gui_msg_fmt="nowy_format".
.SS gui_msg() {}
Jeżeli użytkownik chce podmienić libnotify na np. zenity, może to zrobić nadpisująć tą funkcję swoją własną. Pierwszy parametr to typ czyli [0-255] lub "raport". Drugi parametr to treść.
.SS custom_raport_msg() {}
Za pomocą tej funkcji użytkownik może podmienić treść raportu na np. bardziej treściwy niż jest to możliwe przy użyciu zmiennej `msg_raport'. Gdyby jednak twoja funkcja nie działała prawidłowo to po return większym niż jeden, tekst nie zostanie nadpisany. Kombinajca z gui_msg powinna dać interesujące możliwości. Podstawowe zmienne to $files (nazwy plików), $file_stat (ich status).
.SH TAGI
.SS Tagi dla msg_raport:
%d ilość pomyślnie pobranych napisów,
.br
%n ilość noepobranych napisów,
.br
%a ilość wszystkich razem.
.SS Tagi dla msg_status:
%d id pliku,
.br
%f nazwa plik,
.br
%e numer błędu.
.SS Wspólne tagi:
%b czcionka pogrubiona,
.br
%i czcionka pochylona,
.br
%u czcionka podkreślona,
.br
%0 kolor czarny,
.br
%1 kolor czerwony,
.br
%2 kolor zielony,
.br
%3 kolor żółty,
.br
%4 kolor niebieski,
.br
%5 kolor pomarańczowy,
.br
%6 kolor wyblakło-niebieski,
.br
%7 kolor biały,
.br
%8 domyślny kolory czcionki,
.br
%9 domyślny kolory czcionki.
.SH BŁĘDY
Znalazłaś/eś jakiś błąd - wypełnij formularz dostępny na stronie projektu.
.SH ZOBACZ TEŻ
.BR napi-bash (1)
.SH AUTORZY
Krzysztof (3ED) AS  -- krzysztof1987  [na]  gmail  [kropka]  com
.PP
Strona projektu: https://3ed.github.io/napi-bash
.fi
.PP
.B Program został wykonany przy użyciu tych narzędzi:
    bash      - 99.(9)% całego kodu
    curl      - domyślny agent pobierania
    dd        - wczytywanie określonej ilości bajtów pliku
    md5sum    - sumy kontrolne md5
.fi
.PP
.B Narzędzia opcjonalne:
    iconv     - zmiana kodowania czcionek
    subotage  - konwertowanie formatu napisów
    libnotify - wyświetlanie komunikatów na pulpicie
.fi
